apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "encounter-stack.fullname" . }}-backend
  labels:
    {{- include "encounter-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "encounter-stack.name" . }}-backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "encounter-stack.name" . }}-backend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
              {{- range .Values.backend.imagePullSecrets }}
        - name: {{ .name }}
              {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
              name: http
          env:
            - name: ConnectionStrings__MongoDb
              value: >-
                mongodb://encounters-mongodb:{{ .Values.mongodb.port }}
            - name: MEDIA_DIR
              value: {{ .Values.backend.mediaMountPath | quote }}
            {{- range $k, $v := .Values.backend.extraEnv }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          volumeMounts:
            - name: wwwroot
              mountPath: /app/wwwroot
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
      volumes:
        - name: wwwroot
          persistentVolumeClaim:
            claimName: {{ include "encounter-stack.fullname" . }}-wwwroot