{{- if .Values.ingress.frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "encounter-stack.fullname" . }}-frontend
  labels:
    {{- include "encounter-stack.labels" . | nindent 4 }}
  {{- with .Values.ingress.frontend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.frontend.className }}
  ingressClassName: {{ .Values.ingress.frontend.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.frontend.host | quote }}
      http:
        paths:
          - path: /monster-images
            pathType: Prefix
            backend:
              service:
                name: {{ include "encounter-stack.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "encounter-stack.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.port }}
  {{- if .Values.ingress.frontend.tls }}
  tls:
    {{- toYaml .Values.ingress.frontend.tls | nindent 4 }}
  {{- end }}
{{- end }}
