apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "above.fullname" . }}-backend
  labels:
    {{- include "above.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "above.name" . }}-backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "above.name" . }}-backend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
              {{- range .Values.backend.imagePullSecrets }}
        - name: {{ .name }}
              {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
              name: http
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Host={{ include "above.fullname" . }}-postgres;Port={{ .Values.postgres.port }};Database={{ .Values.postgres.database }};Username={{ .Values.postgres.username }};Password={{ .Values.postgres.password }}"
            - name: MEDIA_DIR
              value: {{ .Values.backend.mediaMountPath | quote }}
            {{- range $k, $v := .Values.backend.extraEnv }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}