apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "above.fullname" . }}-frontend
  labels:
    {{- include "above.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "above.name" . }}-frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "above.name" . }}-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
              {{- range .Values.backend.imagePullSecrets }}
        - name: {{ .name }}
              {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
              name: http
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
