{{- if .Values.ingress.backend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "above.fullname" . }}-backend
  labels:
    {{- include "above.labels" . | nindent 4 }}
  {{- with .Values.ingress.backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.backend.className }}
  ingressClassName: {{ .Values.ingress.backend.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.backend.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "above.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.port }}
  {{- if .Values.ingress.backend.tls }}
  tls:
    {{- toYaml .Values.ingress.backend.tls | nindent 4 }}
  {{- end }}
{{- end }}
